# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowmatematykana5.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowMatematykaNa5(object):
    def setupUi(self, MainWindowMatematykaNa5):
        MainWindowMatematykaNa5.setObjectName("MainWindowMatematykaNa5")
        MainWindowMatematykaNa5.resize(1147, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindowMatematykaNa5)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.horizontalLayout_controls = QtWidgets.QHBoxLayout()
        self.horizontalLayout_controls.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_controls.setSpacing(20)
        self.horizontalLayout_controls.setObjectName("horizontalLayout_controls")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_controls.addItem(spacerItem)
        self.pushButton_hint = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_hint.setFont(font)
        self.pushButton_hint.setObjectName("pushButton_hint")
        self.horizontalLayout_controls.addWidget(self.pushButton_hint)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_controls.addItem(spacerItem1)
        self.pushButton_check = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_check.setFont(font)
        self.pushButton_check.setObjectName("pushButton_check")
        self.horizontalLayout_controls.addWidget(self.pushButton_check)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_controls.addItem(spacerItem2)
        self.gridLayout_main.addLayout(self.horizontalLayout_controls, 3, 1, 1, 1)
        self.label_growing_image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_growing_image.sizePolicy().hasHeightForWidth())
        self.label_growing_image.setSizePolicy(sizePolicy)
        self.label_growing_image.setMinimumSize(QtCore.QSize(150, 0))
        self.label_growing_image.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_growing_image.setFont(font)
        self.label_growing_image.setText("")
        self.label_growing_image.setScaledContents(False)
        self.label_growing_image.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_growing_image.setObjectName("label_growing_image")
        self.gridLayout_main.addWidget(self.label_growing_image, 0, 0, 5, 1)
        self.horizontalLayout_comment = QtWidgets.QHBoxLayout()
        self.horizontalLayout_comment.setObjectName("horizontalLayout_comment")
        self.label_comment = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_comment.setFont(font)
        self.label_comment.setAlignment(QtCore.Qt.AlignCenter)
        self.label_comment.setObjectName("label_comment")
        self.horizontalLayout_comment.addWidget(self.label_comment)
        self.gridLayout_main.addLayout(self.horizontalLayout_comment, 2, 1, 1, 1)
        self.horizontalLayout_equation = QtWidgets.QHBoxLayout()
        self.horizontalLayout_equation.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_equation.setSpacing(30)
        self.horizontalLayout_equation.setObjectName("horizontalLayout_equation")
        self.label_number_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(68)
        font.setBold(True)
        font.setWeight(75)
        self.label_number_1.setFont(font)
        self.label_number_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_1.setObjectName("label_number_1")
        self.horizontalLayout_equation.addWidget(self.label_number_1)
        self.label_operation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(68)
        font.setBold(True)
        font.setWeight(75)
        self.label_operation.setFont(font)
        self.label_operation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_operation.setObjectName("label_operation")
        self.horizontalLayout_equation.addWidget(self.label_operation)
        self.label_number_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(68)
        font.setBold(True)
        font.setWeight(75)
        self.label_number_2.setFont(font)
        self.label_number_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_2.setObjectName("label_number_2")
        self.horizontalLayout_equation.addWidget(self.label_number_2)
        self.label_equals = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(68)
        font.setBold(True)
        font.setWeight(75)
        self.label_equals.setFont(font)
        self.label_equals.setAlignment(QtCore.Qt.AlignCenter)
        self.label_equals.setObjectName("label_equals")
        self.horizontalLayout_equation.addWidget(self.label_equals)
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(68)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_result.setFont(font)
        self.textEdit_result.setObjectName("textEdit_result")
        self.horizontalLayout_equation.addWidget(self.textEdit_result)
        self.gridLayout_main.addLayout(self.horizontalLayout_equation, 1, 1, 1, 1)
        self.horizontalLayout_score = QtWidgets.QHBoxLayout()
        self.horizontalLayout_score.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_score.setObjectName("horizontalLayout_score")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_score.setFont(font)
        self.label_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score.setObjectName("label_score")
        self.horizontalLayout_score.addWidget(self.label_score)
        self.gridLayout_main.addLayout(self.horizontalLayout_score, 4, 1, 1, 1)
        self.horizontalLayout_description = QtWidgets.QHBoxLayout()
        self.horizontalLayout_description.setObjectName("horizontalLayout_description")
        self.label_description = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.horizontalLayout_description.addWidget(self.label_description)
        self.gridLayout_main.addLayout(self.horizontalLayout_description, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_main)
        MainWindowMatematykaNa5.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowMatematykaNa5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1147, 21))
        self.menubar.setObjectName("menubar")
        self.menuGra = QtWidgets.QMenu(self.menubar)
        self.menuGra.setObjectName("menuGra")
        self.menuTylko_dodawanie = QtWidgets.QMenu(self.menuGra)
        self.menuTylko_dodawanie.setObjectName("menuTylko_dodawanie")
        self.menuTylko_odejmowanie = QtWidgets.QMenu(self.menuGra)
        self.menuTylko_odejmowanie.setObjectName("menuTylko_odejmowanie")
        self.menuDod_Od = QtWidgets.QMenu(self.menuGra)
        self.menuDod_Od.setObjectName("menuDod_Od")
        self.menuTylko_mnozenie = QtWidgets.QMenu(self.menuGra)
        self.menuTylko_mnozenie.setObjectName("menuTylko_mnozenie")
        self.menuKonfiguracja = QtWidgets.QMenu(self.menubar)
        self.menuKonfiguracja.setObjectName("menuKonfiguracja")
        self.menuProfil = QtWidgets.QMenu(self.menubar)
        self.menuProfil.setObjectName("menuProfil")
        MainWindowMatematykaNa5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowMatematykaNa5)
        self.statusbar.setObjectName("statusbar")
        MainWindowMatematykaNa5.setStatusBar(self.statusbar)
        self.actionKonfiguruj_gre = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionKonfiguruj_gre.setObjectName("actionKonfiguruj_gre")
        self.actionDodawanie_10 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_10.setObjectName("actionDodawanie_10")
        self.actionDodawanie_20 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_20.setObjectName("actionDodawanie_20")
        self.actionDodawanie_30 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_30.setObjectName("actionDodawanie_30")
        self.actionDodawanie_40 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_40.setObjectName("actionDodawanie_40")
        self.actionDodawanie_50 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_50.setObjectName("actionDodawanie_50")
        self.actionDodawanie_zakres = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_zakres.setObjectName("actionDodawanie_zakres")
        self.actionOdejmowanie_10 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_10.setObjectName("actionOdejmowanie_10")
        self.actionOdejmowanie_20 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_20.setObjectName("actionOdejmowanie_20")
        self.actionOdejmowanie_30 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_30.setObjectName("actionOdejmowanie_30")
        self.actionOdejmowanie_40 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_40.setObjectName("actionOdejmowanie_40")
        self.actionOdejmowanie_50 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_50.setObjectName("actionOdejmowanie_50")
        self.actionOdejmowanie_zakres = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_zakres.setObjectName("actionOdejmowanie_zakres")
        self.actionDod_Od_10 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_10.setObjectName("actionDod_Od_10")
        self.actionDod_Od_20 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_20.setObjectName("actionDod_Od_20")
        self.actionDod_Od_30 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_30.setObjectName("actionDod_Od_30")
        self.actionDod_Od_40 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_40.setObjectName("actionDod_Od_40")
        self.actionDod_Od_50 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_50.setObjectName("actionDod_Od_50")
        self.actionDod_Od_zakres = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_zakres.setObjectName("actionDod_Od_zakres")
        self.actionKoniec = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionKoniec.setObjectName("actionKoniec")
        self.actionDomyslna_konfiguracja_gier = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDomyslna_konfiguracja_gier.setObjectName("actionDomyslna_konfiguracja_gier")
        self.actionWybierz_gracza = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionWybierz_gracza.setObjectName("actionWybierz_gracza")
        self.actionNowy_gracz = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionNowy_gracz.setObjectName("actionNowy_gracz")
        self.actionDzwiek_wlaczony = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDzwiek_wlaczony.setCheckable(True)
        self.actionDzwiek_wlaczony.setChecked(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Priv/MyProjects/LearnMath/resources/sound_high.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDzwiek_wlaczony.setIcon(icon)
        self.actionDzwiek_wlaczony.setObjectName("actionDzwiek_wlaczony")
        self.actionMnozenie_20 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_20.setObjectName("actionMnozenie_20")
        self.actionMnozenie_30 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_30.setObjectName("actionMnozenie_30")
        self.actionMnozenie_40 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_40.setObjectName("actionMnozenie_40")
        self.actionMnozenie_50 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_50.setObjectName("actionMnozenie_50")
        self.actionMnozenie_100 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_100.setObjectName("actionMnozenie_100")
        self.actionMnozenie_zakres = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_zakres.setObjectName("actionMnozenie_zakres")
        self.actionOdejmowanie_100 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_100.setObjectName("actionOdejmowanie_100")
        self.actionDodawanie_100 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_100.setObjectName("actionDodawanie_100")
        self.actionDod_Od_100 = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDod_Od_100.setObjectName("actionDod_Od_100")
        self.actionDodawanie_popraw = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionDodawanie_popraw.setObjectName("actionDodawanie_popraw")
        self.actionOdejmowanie_popraw = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionOdejmowanie_popraw.setObjectName("actionOdejmowanie_popraw")
        self.actionMnozenie_popraw = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_popraw.setObjectName("actionMnozenie_popraw")
        self.actionMnozenie_przez_n = QtWidgets.QAction(MainWindowMatematykaNa5)
        self.actionMnozenie_przez_n.setObjectName("actionMnozenie_przez_n")
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_10)
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_20)
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_30)
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_40)
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_50)
        self.menuTylko_dodawanie.addSeparator()
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_100)
        self.menuTylko_dodawanie.addSeparator()
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_zakres)
        self.menuTylko_dodawanie.addSeparator()
        self.menuTylko_dodawanie.addAction(self.actionDodawanie_popraw)
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_10)
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_20)
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_30)
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_40)
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_50)
        self.menuTylko_odejmowanie.addSeparator()
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_100)
        self.menuTylko_odejmowanie.addSeparator()
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_zakres)
        self.menuTylko_odejmowanie.addSeparator()
        self.menuTylko_odejmowanie.addAction(self.actionOdejmowanie_popraw)
        self.menuDod_Od.addAction(self.actionDod_Od_10)
        self.menuDod_Od.addAction(self.actionDod_Od_20)
        self.menuDod_Od.addAction(self.actionDod_Od_30)
        self.menuDod_Od.addAction(self.actionDod_Od_40)
        self.menuDod_Od.addAction(self.actionDod_Od_50)
        self.menuDod_Od.addSeparator()
        self.menuDod_Od.addAction(self.actionDod_Od_100)
        self.menuDod_Od.addSeparator()
        self.menuDod_Od.addAction(self.actionDod_Od_zakres)
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_20)
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_30)
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_40)
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_50)
        self.menuTylko_mnozenie.addSeparator()
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_100)
        self.menuTylko_mnozenie.addSeparator()
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_przez_n)
        self.menuTylko_mnozenie.addSeparator()
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_zakres)
        self.menuTylko_mnozenie.addSeparator()
        self.menuTylko_mnozenie.addAction(self.actionMnozenie_popraw)
        self.menuGra.addAction(self.menuTylko_dodawanie.menuAction())
        self.menuGra.addAction(self.menuTylko_odejmowanie.menuAction())
        self.menuGra.addAction(self.menuTylko_mnozenie.menuAction())
        self.menuGra.addSeparator()
        self.menuGra.addAction(self.menuDod_Od.menuAction())
        self.menuGra.addSeparator()
        self.menuGra.addAction(self.actionKonfiguruj_gre)
        self.menuGra.addSeparator()
        self.menuGra.addAction(self.actionKoniec)
        self.menuKonfiguracja.addAction(self.actionDomyslna_konfiguracja_gier)
        self.menuKonfiguracja.addSeparator()
        self.menuKonfiguracja.addAction(self.actionDzwiek_wlaczony)
        self.menuProfil.addAction(self.actionWybierz_gracza)
        self.menuProfil.addSeparator()
        self.menuProfil.addAction(self.actionNowy_gracz)
        self.menuProfil.addSeparator()
        # self.menubar.addAction(self.menuProfil.menuAction())
        self.menubar.addAction(self.menuGra.menuAction())
        self.menubar.addAction(self.menuKonfiguracja.menuAction())

        self.retranslateUi(MainWindowMatematykaNa5)
        QtCore.QMetaObject.connectSlotsByName(MainWindowMatematykaNa5)

    def retranslateUi(self, MainWindowMatematykaNa5):
        _translate = QtCore.QCoreApplication.translate
        MainWindowMatematykaNa5.setWindowTitle(_translate("MainWindowMatematykaNa5", "Matematyka na 5!"))
        self.pushButton_hint.setText(_translate("MainWindowMatematykaNa5", "  Podpowiedź  "))
        self.pushButton_check.setText(_translate("MainWindowMatematykaNa5", "  Sprawdź  "))
        self.label_comment.setText(_translate("MainWindowMatematykaNa5", "Brawo!"))
        self.label_number_1.setText(_translate("MainWindowMatematykaNa5", "123"))
        self.label_operation.setText(_translate("MainWindowMatematykaNa5", "+"))
        self.label_number_2.setText(_translate("MainWindowMatematykaNa5", "234"))
        self.label_equals.setText(_translate("MainWindowMatematykaNa5", " = "))
        self.textEdit_result.setHtml(_translate("MainWindowMatematykaNa5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:68pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:72pt;\">3570</span></p></body></html>"))
        self.label_score.setText(_translate("MainWindowMatematykaNa5", "Działanie: 10 z 10            Poprawnie: 10           Błędnie: 0   \n"
"\n"
"  Świetny wynik, gratulacje!"))
        self.label_description.setText(_translate("MainWindowMatematykaNa5", "Wpisz wynik działania:"))
        self.menuGra.setTitle(_translate("MainWindowMatematykaNa5", "Gra"))
        self.menuTylko_dodawanie.setTitle(_translate("MainWindowMatematykaNa5", "Tylko dodawanie"))
        self.menuTylko_odejmowanie.setTitle(_translate("MainWindowMatematykaNa5", "Tylko odejmowanie"))
        self.menuDod_Od.setTitle(_translate("MainWindowMatematykaNa5", "Dodawanie i odejmowanie"))
        self.menuTylko_mnozenie.setTitle(_translate("MainWindowMatematykaNa5", "Tylko mnożenie"))
        self.menuKonfiguracja.setTitle(_translate("MainWindowMatematykaNa5", "Opcje"))
        self.menuProfil.setTitle(_translate("MainWindowMatematykaNa5", "Profil"))
        self.actionKonfiguruj_gre.setText(_translate("MainWindowMatematykaNa5", "Konfiguruj grę..."))
        self.actionDodawanie_10.setText(_translate("MainWindowMatematykaNa5", "do 10"))
        self.actionDodawanie_20.setText(_translate("MainWindowMatematykaNa5", "do 20"))
        self.actionDodawanie_30.setText(_translate("MainWindowMatematykaNa5", "do 30"))
        self.actionDodawanie_40.setText(_translate("MainWindowMatematykaNa5", "do 40"))
        self.actionDodawanie_50.setText(_translate("MainWindowMatematykaNa5", "do 50"))
        self.actionDodawanie_zakres.setText(_translate("MainWindowMatematykaNa5", "w wybranym zakresie..."))
        self.actionOdejmowanie_10.setText(_translate("MainWindowMatematykaNa5", "do 10"))
        self.actionOdejmowanie_20.setText(_translate("MainWindowMatematykaNa5", "do 20"))
        self.actionOdejmowanie_30.setText(_translate("MainWindowMatematykaNa5", "do 30"))
        self.actionOdejmowanie_40.setText(_translate("MainWindowMatematykaNa5", "do 40"))
        self.actionOdejmowanie_50.setText(_translate("MainWindowMatematykaNa5", "do 50"))
        self.actionOdejmowanie_zakres.setText(_translate("MainWindowMatematykaNa5", "w wybranym zakresie..."))
        self.actionDod_Od_10.setText(_translate("MainWindowMatematykaNa5", "do 10"))
        self.actionDod_Od_20.setText(_translate("MainWindowMatematykaNa5", "do 20"))
        self.actionDod_Od_30.setText(_translate("MainWindowMatematykaNa5", "do 30"))
        self.actionDod_Od_40.setText(_translate("MainWindowMatematykaNa5", "do 40"))
        self.actionDod_Od_50.setText(_translate("MainWindowMatematykaNa5", "do 50"))
        self.actionDod_Od_zakres.setText(_translate("MainWindowMatematykaNa5", "w wybranym zakresie..."))
        self.actionKoniec.setText(_translate("MainWindowMatematykaNa5", "Koniec"))
        self.actionDomyslna_konfiguracja_gier.setText(_translate("MainWindowMatematykaNa5", "Domyślna konfiguracja gier"))
        self.actionWybierz_gracza.setText(_translate("MainWindowMatematykaNa5", "Wybierz gracza.."))
        self.actionNowy_gracz.setText(_translate("MainWindowMatematykaNa5", "Nowy gracz..."))
        self.actionDzwiek_wlaczony.setText(_translate("MainWindowMatematykaNa5", "Dźwięk: włączony"))
        self.actionDzwiek_wlaczony.setStatusTip(_translate("MainWindowMatematykaNa5", "Włącz lub wyłącz dźwięki podczas gry"))
        self.actionMnozenie_20.setText(_translate("MainWindowMatematykaNa5", "do 20"))
        self.actionMnozenie_30.setText(_translate("MainWindowMatematykaNa5", "do 30"))
        self.actionMnozenie_40.setText(_translate("MainWindowMatematykaNa5", "do 40"))
        self.actionMnozenie_50.setText(_translate("MainWindowMatematykaNa5", "do 50"))
        self.actionMnozenie_100.setText(_translate("MainWindowMatematykaNa5", "do 100"))
        self.actionMnozenie_zakres.setText(_translate("MainWindowMatematykaNa5", "w wybranym zakresie..."))
        self.actionOdejmowanie_100.setText(_translate("MainWindowMatematykaNa5", "do 100"))
        self.actionDodawanie_100.setText(_translate("MainWindowMatematykaNa5", "do 100"))
        self.actionDod_Od_100.setText(_translate("MainWindowMatematykaNa5", "do 100"))
        self.actionDodawanie_popraw.setText(_translate("MainWindowMatematykaNa5", "popraw błędy..."))
        self.actionOdejmowanie_popraw.setText(_translate("MainWindowMatematykaNa5", "popraw błędy..."))
        self.actionMnozenie_popraw.setText(_translate("MainWindowMatematykaNa5", "popraw blędy..."))
        self.actionMnozenie_przez_n.setText(_translate("MainWindowMatematykaNa5", "przez wybraną liczbę..."))

