# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 211)
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_group = QtWidgets.QVBoxLayout()
        self.verticalLayout_group.setObjectName("verticalLayout_group")
        self.horizontalLayout_questions = QtWidgets.QHBoxLayout()
        self.horizontalLayout_questions.setSpacing(20)
        self.horizontalLayout_questions.setObjectName("horizontalLayout_questions")
        self.label_questions = QtWidgets.QLabel(Dialog)
        self.label_questions.setMinimumSize(QtCore.QSize(120, 0))
        self.label_questions.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_questions.setObjectName("label_questions")
        self.horizontalLayout_questions.addWidget(self.label_questions)
        self.plainTextEdit_questions = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_questions.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_questions.setSizePolicy(sizePolicy)
        self.plainTextEdit_questions.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_questions.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit_questions.setObjectName("plainTextEdit_questions")
        self.horizontalLayout_questions.addWidget(self.plainTextEdit_questions)
        self.verticalLayout_group.addLayout(self.horizontalLayout_questions)
        self.horizontalLayout_hints = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hints.setSpacing(20)
        self.horizontalLayout_hints.setObjectName("horizontalLayout_hints")
        self.label_hints = QtWidgets.QLabel(Dialog)
        self.label_hints.setMinimumSize(QtCore.QSize(120, 0))
        self.label_hints.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_hints.setObjectName("label_hints")
        self.horizontalLayout_hints.addWidget(self.label_hints)
        self.comboBox_hints = QtWidgets.QComboBox(Dialog)
        self.comboBox_hints.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_hints.setMaximumSize(QtCore.QSize(200, 30))
        self.comboBox_hints.setObjectName("comboBox_hints")
        # self.comboBox_hints.addItem("")
        # self.comboBox_hints.addItem("")
        # self.comboBox_hints.addItem("")
        self.horizontalLayout_hints.addWidget(self.comboBox_hints)
        self.plainTextEdit_hints = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_hints.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_hints.setSizePolicy(sizePolicy)
        self.plainTextEdit_hints.setMinimumSize(QtCore.QSize(30, 30))
        self.plainTextEdit_hints.setMaximumSize(QtCore.QSize(100, 30))
        self.plainTextEdit_hints.setObjectName("plainTextEdit_hints")
        self.horizontalLayout_hints.addWidget(self.plainTextEdit_hints)
        self.verticalLayout_group.addLayout(self.horizontalLayout_hints)
        self.horizontalLayout_player = QtWidgets.QHBoxLayout()
        self.horizontalLayout_player.setSpacing(20)
        self.horizontalLayout_player.setObjectName("horizontalLayout_player")
        self.label_player = QtWidgets.QLabel(Dialog)
        self.label_player.setMinimumSize(QtCore.QSize(120, 0))
        self.label_player.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_player.setObjectName("label_player")
        self.horizontalLayout_player.addWidget(self.label_player)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_player.addWidget(self.plainTextEdit)
        self.verticalLayout_group.addLayout(self.horizontalLayout_player)
        self.horizontalLayout_sound = QtWidgets.QHBoxLayout()
        self.horizontalLayout_sound.setObjectName("horizontalLayout_sound")
        self.label_sounds = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sounds.sizePolicy().hasHeightForWidth())
        self.label_sounds.setSizePolicy(sizePolicy)
        self.label_sounds.setMinimumSize(QtCore.QSize(134, 0))
        self.label_sounds.setObjectName("label_sounds")
        self.horizontalLayout_sound.addWidget(self.label_sounds)
        self.checkBox_sounds = QtWidgets.QCheckBox(Dialog)
        self.checkBox_sounds.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_sounds.setTristate(False)
        self.checkBox_sounds.setObjectName("checkBox_sounds")
        self.horizontalLayout_sound.addWidget(self.checkBox_sounds)
        self.verticalLayout_group.addLayout(self.horizontalLayout_sound)
        self.verticalLayout_2.addLayout(self.verticalLayout_group)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_sounds.setBuddy(self.checkBox_sounds)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_questions.setText(_translate("Dialog", "Liczba równań w 1 grze"))
        self.plainTextEdit_questions.setPlainText(_translate("Dialog", "20"))
        self.label_hints.setText(_translate("Dialog", "Podpowiedzi"))
        self.comboBox_hints.setCurrentText(_translate("Dialog", "Zawsze dostępne"))
        # self.comboBox_hints.setItemText(0, _translate("Dialog", "Zawsze dostępne"))
        # self.comboBox_hints.setItemText(1, _translate("Dialog", "Max liczba podpowiedzi"))
        # self.comboBox_hints.setItemText(2, _translate("Dialog", "Max liczba popdpowiedzi = % równań w 1 grze"))
        self.label_player.setText(_translate("Dialog", "Nazwa gracza"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Hubert"))
        self.label_sounds.setText(_translate("Dialog", "&Dźwięk włączony"))
        self.checkBox_sounds.setText(_translate("Dialog", " "))

